DROP DATABASE IF EXIST  employee_db;
CREATE DATABASE employee_db;
USE employee_db;


CREATE TABLE department (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL
)